name: Deploy pages

on:
  push:
    branches: [ build_setup ]
  pull_request:
    branches: [ build_setup ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install ğŸ”§
        run: npm install
      - name: Build (1/2) ğŸ”§
        run: npm run build
      - name: Test setup
        run: cp -r dist/* docs/
      - name: Test setup
        run: ls -al
      - name: Deploy ğŸš€
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: 'docs'
          author_name: 'Release Bot'
          author_email: 'dotone-www-git@dot0x01.com'
          message: 'Release [ci skip]'
